repos:
-   repo: https://github.com/ikamensh/flynt
    rev: ''  # Specify a specific version if desired
    hooks:
    -   id: flynt
        args: [ "--line-length", "160"]  # Flynt does not support pyproject.toml in special locations

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        types: [python]
        args: ["--config", "package/pyproject.toml"]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--settings-path", "package/pyproject.toml"]

# exclude python 2 code which cannot be dealt with black
exclude: |
    (?x)(
        ^pandaharvester/harvestermonitor/arc_monitor.py|
        ^pandaharvester/harvestermisc/arc_utils.py|
        ^pandaharvester/harvesterpayload/simple_wrapper_mpi.py|
        ^pandaharvester/harvestersubmitter/apfgrid_submitter.py|
        ^pandaharvester/harvestertest/dumpTable.py|
        ^pandaharvester/harvestertest/getQueuedata.py|
        ^pandaharvester/harvestermessenger/arc_messenger.py|
        ^pandaharvester/harvestersubmitter/arc_submitter.py|
        ^pandaharvester/harvestertest/stageOutTest_globus.py|
        ^pandaharvester/harvestertest/stageInTest_go_bulk_preparator.py|
        ^pandaharvester/harvesterpayload/ATLAS_simple_wrapper_mpi.py|
        ^pandaharvester/harvestercloud/google_startup_script.py|
        ^&
    )